const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
export default {async fetch(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;
try{
if(p==="/api/reports"&&m==="GET"){let {results}=await env.DB.prepare("SELECT id,meeting_no,title,meeting_date,meeting_time,location,attendees,agenda,summary,resolutions,followups,prepared_by,head_note,group_head_note,approval_note,status,created_at,updated_at,submitted_at,checked_at,approved_at,signed_at,year_be,sequence_no,folder_url,files_json,recorder_signed_at,admin_signed_at FROM meeting_reports ORDER BY COALESCE(year_be,0) DESC,COALESCE(sequence_no,999),meeting_date").all();results=results.map(r=>({...r,files_json:JSON.parse(r.files_json||"[]")}));return j({reports:results})}
if(p==="/api/reports"&&m==="POST"){const b=await req.json(),rid=id(),t=now(),yb=Number(b.year_be||2569),sn=Number(b.sequence_no||1);await env.DB.prepare("INSERT INTO meeting_reports(id,meeting_no,title,meeting_date,meeting_time,location,attendees,agenda,summary,resolutions,followups,prepared_by,status,created_by,created_at,updated_at,year_be,sequence_no,folder_url,files_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?,?,?,?,?,'[]')").bind(rid,b.meeting_no||`ครั้งที่ ${sn}/${yb}`,b.title||"การประชุมกลุ่มงานพัสดุ",b.meeting_date||null,b.meeting_time||"",b.location||"",b.attendees||"",b.agenda||"",b.summary||"",b.resolutions||"",b.followups||"",b.prepared_by||"ผู้จัดทำ","ผู้จัดทำ",t,t,yb,sn,b.folder_url||null).run();return j({report:{id:rid}},201)}
let x=p.match(/^\/api\/reports\/([^/]+)$/);if(x&&m==="PUT"){const b=await req.json(),t=now();await env.DB.prepare("UPDATE meeting_reports SET status=?,head_note=COALESCE(?,head_note),group_head_note=COALESCE(?,group_head_note),approval_note=COALESCE(?,approval_note),updated_at=? WHERE id=?").bind(b.status,b.head_note??null,b.group_head_note??null,b.approval_note??null,t,x[1]).run();return j({report:{id:x[1],status:b.status}})}
x=p.match(/^\/api\/attendance\/([^/]+)\/meta$/);if(x&&m==="GET"){const r=await env.DB.prepare("SELECT id,meeting_no,title,meeting_date,meeting_time,location FROM meeting_reports WHERE id=?").bind(x[1]).first();return r?j({meeting:r}):j({error:"ไม่พบการประชุม"},404)}
x=p.match(/^\/api\/attendance\/([^/]+)(?:\/full)?$/);if(x&&m==="GET"){const {results}=await env.DB.prepare("SELECT id,name,role,sort_order,attendance_status,note,signed_at,signature_data FROM meeting_attendance WHERE report_id=? ORDER BY sort_order,name").bind(x[1]).all();return j({attendance:results.map(r=>({...r,has_signature:!!r.signature_data}))})}
if(x&&m==="POST"){const b=await req.json();await env.DB.prepare("UPDATE meeting_attendance SET attendance_status=?,signature_data=?,note=?,signed_at=? WHERE id=? AND report_id=?").bind(b.status,b.signature_data,b.note||"",now(),b.id,x[1]).run();return j({attendance:{id:b.id,attendance_status:b.status}})}
x=p.match(/^\/api\/reports\/([^/]+)\/sign$/);if(x&&m==="POST"){const b=await req.json(),col=b.role==="recorder"?"recorder_signature_data":"admin_signature_data",tc=b.role==="recorder"?"recorder_signed_at":"admin_signed_at";await env.DB.prepare(`UPDATE meeting_reports SET ${col}=?,${tc}=?,updated_at=? WHERE id=?`).bind(b.signature_data,now(),now(),x[1]).run();return j({report:{id:x[1]}})}
return env.ASSETS.fetch(req)}catch(e){return j({error:e.message},500)}}};