// trigger Cloudflare build for neon-test
import { neon } from '@neondatabase/serverless';
const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
export default {async fetch(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;
try{
if(p==="/api/neon-test"&&m==="GET"){
  const sql=neon(env.DATABASE_URL);
  const rows=await sql`SELECT COUNT(*)::int AS reports FROM meeting_reports`;
  return j({ok:true,backend:"neon",reports:Number(rows?.[0]?.reports||0)});
}
if(p==="/api/neon-test"&&m==="POST"){
  const sql=neon(env.DATABASE_URL),rid=id(),t=now();
  await sql`INSERT INTO meeting_reports(id,meeting_no,title,status,created_by,created_at,updated_at,year_be,sequence_no,files_json) VALUES(${rid},${"ครั้งที่ 999/2569"},${"ทดสอบ Cloudflare Worker เชื่อม Neon"},'draft',${"neon-test"},${t},${t},${2569},${999},'[]'::jsonb)`;
  return j({ok:true,backend:"neon",id:rid},201);
}
if(p==="/api/neon-write-test"&&m==="GET"){
  const sql=neon(env.DATABASE_URL),rid=id(),t=now();
  await sql`INSERT INTO meeting_reports(id,meeting_no,title,status,created_by,created_at,updated_at,year_be,sequence_no,files_json) VALUES(${rid},${"ครั้งที่ 999/2569"},${"ทดสอบเขียน Cloudflare ไป Neon"},'draft',${"neon-write-test"},${t},${t},${2569},${999},'[]'::jsonb)`;
  const rows=await sql`SELECT id,title,created_by,created_at FROM meeting_reports WHERE id=${rid}`;
  return j({ok:true,backend:"neon",write:true,row:rows[0]});
}

if(p==="/api/reports"&&m==="GET"){const sql=neon(env.DATABASE_URL);const results=await sql`SELECT id,meeting_no,title,meeting_date,meeting_time,location,attendees,agenda,summary,resolutions,followups,prepared_by,head_note,group_head_note,approval_note,status,created_at,updated_at,submitted_at,checked_at,approved_at,signed_at,year_be,sequence_no,folder_url,files_json,recorder_signed_at,admin_signed_at FROM meeting_reports ORDER BY COALESCE(year_be,0) DESC,COALESCE(sequence_no,999),meeting_date`;return j({reports:results.map(r=>({...r,files_json:Array.isArray(r.files_json)?r.files_json:[]})),backend:"neon"})}
if(p==="/api/migration-status"&&m==="GET"){const r=await env.DB.prepare("SELECT COUNT(*) AS n FROM meeting_reports").first(),a=await env.DB.prepare("SELECT COUNT(*) AS n FROM meeting_attendance").first();return j({reports:Number(r?.n||0),attendance:Number(a?.n||0)})}
if(p==="/api/reports"&&m==="POST"){const sql=neon(env.DATABASE_URL);const b=await req.json(),rid=id(),t=now(),yb=Number(b.year_be||2569),sn=Number(b.sequence_no||1);await sql`INSERT INTO meeting_reports(id,meeting_no,title,meeting_date,meeting_time,location,attendees,agenda,summary,resolutions,followups,prepared_by,status,created_by,created_at,updated_at,year_be,sequence_no,folder_url,files_json) VALUES(${rid},${b.meeting_no||`ครั้งที่ ${sn}/${yb}`},${b.title||"การประชุมกลุ่มงานพัสดุ"},${b.meeting_date||null},${b.meeting_time||""},${b.location||""},${b.attendees||""},${b.agenda||""},${b.summary||""},${b.resolutions||""},${b.followups||""},${b.prepared_by||"ผู้จัดทำ"},'draft',${"ผู้จัดทำ"},${t},${t},${yb},${sn},${b.folder_url||null},'[]'::jsonb)`;return j({report:{id:rid},backend:"neon"},201)}
let x=p.match(/^\/api\/reports\/([^/]+)$/);if(x&&m==="PUT"){const b=await req.json(),t=now(),s=b.status;await env.DB.prepare("UPDATE meeting_reports SET status=?,head_note=COALESCE(?,head_note),group_head_note=COALESCE(?,group_head_note),approval_note=COALESCE(?,approval_note),submitted_at=CASE WHEN ?='pending_head' THEN COALESCE(submitted_at,?) ELSE submitted_at END,checked_at=CASE WHEN ?='pending_group_head' THEN COALESCE(checked_at,?) ELSE checked_at END,approved_at=CASE WHEN ?='approved' THEN COALESCE(approved_at,?) ELSE approved_at END,signed_at=CASE WHEN ? IN ('completed','signed') THEN COALESCE(signed_at,?) ELSE signed_at END,updated_at=? WHERE id=?").bind(s,b.head_note??null,b.group_head_note??null,b.approval_note??null,s,t,s,t,s,t,s,t,t,x[1]).run();return j({report:{id:x[1],status:s}})}
x=p.match(/^\/api\/attendance\/([^/]+)\/meta$/);if(x&&m==="GET"){const r=await env.DB.prepare("SELECT id,meeting_no,title,meeting_date,meeting_time,location FROM meeting_reports WHERE id=?").bind(x[1]).first();return r?j({meeting:r}):j({error:"ไม่พบการประชุม"},404)}
x=p.match(/^\/api\/attendance\/([^/]+)(?:\/(full))?$/);if(x&&m==="GET"){const full=!!x[2];const sql=full?"SELECT id,name,role,sort_order,attendance_status,note,signed_at,signature_data FROM meeting_attendance WHERE report_id=? ORDER BY sort_order,name":"SELECT id,name,role,sort_order,attendance_status,note,signed_at,(signature_data IS NOT NULL AND signature_data <> '') AS has_signature FROM meeting_attendance WHERE report_id=? ORDER BY sort_order,name";const {results}=await env.DB.prepare(sql).bind(x[1]).all();return j({attendance:results})}
if(x&&m==="POST"){const b=await req.json(),allowed=new Set(["present","vacation","official","personal","sick"]);if(!b.id||!allowed.has(b.status))return j({error:"ข้อมูลลงชื่อไม่ครบ"},400);if(!b.signature_data||!String(b.signature_data).startsWith("data:image/png;base64,"))return j({error:"กรุณาลงลายมือชื่อในช่องก่อนยืนยัน"},400);if(String(b.signature_data).length>250000)return j({error:"ลายเซ็นมีขนาดใหญ่เกินไป"},413);const r=await env.DB.prepare("UPDATE meeting_attendance SET attendance_status=?,signature_data=?,note=?,signed_at=? WHERE id=? AND report_id=?").bind(b.status,b.signature_data,b.note||"",now(),b.id,x[1]).run();if(!r.meta.changes)return j({error:"ไม่พบรายชื่อ"},404);return j({attendance:{id:b.id,attendance_status:b.status}})}
x=p.match(/^\/api\/reports\/([^/]+)\/sign$/);if(x&&m==="POST"){const b=await req.json();if(!["recorder","admin"].includes(b.role))return j({error:"บทบาทผู้ลงนามไม่ถูกต้อง"},400);if(!b.signature_data||!String(b.signature_data).startsWith("data:image/png;base64,")||String(b.signature_data).length>250000)return j({error:"ลายเซ็นไม่ถูกต้อง"},400);const col=b.role==="recorder"?"recorder_signature_data":"admin_signature_data",tc=b.role==="recorder"?"recorder_signed_at":"admin_signed_at";await env.DB.prepare(`UPDATE meeting_reports SET ${col}=?,${tc}=?,updated_at=? WHERE id=?`).bind(b.signature_data,now(),now(),x[1]).run();return j({report:{id:x[1]}})}
return env.ASSETS.fetch(req)}catch(e){return j({error:e.message},500)}}};